# Assignments-1: Basic Python

## Installing the required libraries

In [116]:
!pip install pymongo

Requirement already satisfied: pymongo in c:\users\deepj\anaconda3\lib\site-packages (3.12.0)

## Importing the libraries

In [125]:
import pymongo
from pymongo import MongoClient
import pandas as pd
import numpy as np

## Connecting to the local MongoDB database

- Instead of creating 100 random sample data, the data is imported to the database from a sample dataset via [GitHub](https://github.com/ivylabs/mongodb-databases-sample) provided by [IvyLabs](http://www.ivy-is.co.uk/).
- Using the `region` collection which has 110 data/objects/rows

In [111]:
db = MongoClient("localhost", 27017).foodmart

## Fetching the data from database and create the dataframe

In [114]:
df = pd.DataFrame(list(db.region.find()))
df

,_id,region_id,sales_city,sales_state_province,sales_district,sales_region,sales_country,sales_district_id
0,53c7c973ccf26e6de850bbf2,0,None,None,No District,No Region,No Country,0
1,53c7c973ccf26e6de850bbf3,1,San Francisco,CA,San Francisco,Central West,USA,123
2,53c7c973ccf26e6de850bbf4,2,Mexico City,DF,Mexico City,Mexico Central,Mexico,118
3,53c7c973ccf26e6de850bbf5,3,Los Angeles,CA,Los Angeles,South West,USA,116
4,53c7c973ccf26e6de850bbf6,4,Guadalajara,Jalisco,Guadalajara,Mexico West,Mexico,114
...,...,...,...,...,...,...,...,...
105,53c7c973ccf26e6de850bf27,105,Shawnee,BC,Victoria,Canada West,Canada,129
106,53c7c973ccf26e6de850bf28,106,San Andres,DF,Mexico City,Mexico Central,Mexico,118
107,53c7c973ccf26e6de850bf29,107,Tixapan,DF,Mexico City,Mexico Central,Mexico,118
108,53c7c973ccf26e6de850bf2a,108,Santa Anita,DF,Mexico City,Mexico Central,Mexico,118
109,53c7c973ccf26e6de850bf2b,109,Santa Fe,DF,Mexico City,Mexico Central,Mexico,118

## Saving the data into a CSV file

In [ ]:
df.to_csv('regions.csv', index=False, encoding='utf-8')

## Reading the CSV file

In [122]:
df = pd.read_csv("regions.csv")

## Adding a new column named "sale_index" at end of the dataframe with randomly generated values

In [133]:
df.assign(sale_index=np.random.rand(110))

,_id,region_id,sales_city,sales_state_province,sales_district,sales_region,sales_country,sales_district_id,sale_index
0,53c7c973ccf26e6de850bbf2,0,None,None,No District,No Region,No Country,0,0.581624
1,53c7c973ccf26e6de850bbf3,1,San Francisco,CA,San Francisco,Central West,USA,123,0.503253
2,53c7c973ccf26e6de850bbf4,2,Mexico City,DF,Mexico City,Mexico Central,Mexico,118,0.102805
3,53c7c973ccf26e6de850bbf5,3,Los Angeles,CA,Los Angeles,South West,USA,116,0.877475
4,53c7c973ccf26e6de850bbf6,4,Guadalajara,Jalisco,Guadalajara,Mexico West,Mexico,114,0.980410
...,...,...,...,...,...,...,...,...,...
105,53c7c973ccf26e6de850bf27,105,Shawnee,BC,Victoria,Canada West,Canada,129,0.860351
106,53c7c973ccf26e6de850bf28,106,San Andres,DF,Mexico City,Mexico Central,Mexico,118,0.891649
107,53c7c973ccf26e6de850bf29,107,Tixapan,DF,Mexico City,Mexico Central,Mexico,118,0.133882
108,53c7c973ccf26e6de850bf2a,108,Santa Anita,DF,Mexico City,Mexico Central,Mexico,118,0.925866
109,53c7c973ccf26e6de850bf2b,109,Santa Fe,DF,Mexico City,Mexico Central,Mexico,118,0.403407

## Printing the top 5 rows

In [134]:
df.head()

,_id,region_id,sales_city,sales_state_province,sales_district,sales_region,sales_country,sales_district_id
0,53c7c973ccf26e6de850bbf2,0,None,None,No District,No Region,No Country,0
1,53c7c973ccf26e6de850bbf3,1,San Francisco,CA,San Francisco,Central West,USA,123
2,53c7c973ccf26e6de850bbf4,2,Mexico City,DF,Mexico City,Mexico Central,Mexico,118
3,53c7c973ccf26e6de850bbf5,3,Los Angeles,CA,Los Angeles,South West,USA,116
4,53c7c973ccf26e6de850bbf6,4,Guadalajara,Jalisco,Guadalajara,Mexico West,Mexico,114

## Printing the dimension of the dataframe/matrix

In [136]:
df.shape

(110, 8)

## Transposing the dataframe

In [142]:
tdf = df.transpose()
tdf

,0,1,2,3,4,5,6,7,8,9,...,100,101,102,103,104,105,106,107,108,109
_id,53c7c973ccf26e6de850bbf2,53c7c973ccf26e6de850bbf3,53c7c973ccf26e6de850bbf4,53c7c973ccf26e6de850bbf5,53c7c973ccf26e6de850bbf6,53c7c973ccf26e6de850bbf7,53c7c973ccf26e6de850bbf8,53c7c973ccf26e6de850bbf9,53c7c973ccf26e6de850bbfa,53c7c973ccf26e6de850bbfb,...,53c7c973ccf26e6de850bf22,53c7c973ccf26e6de850bf23,53c7c973ccf26e6de850bf24,53c7c973ccf26e6de850bf25,53c7c973ccf26e6de850bf26,53c7c973ccf26e6de850bf27,53c7c973ccf26e6de850bf28,53c7c973ccf26e6de850bf29,53c7c973ccf26e6de850bf2a,53c7c973ccf26e6de850bf2b
region_id,0,1,2,3,4,5,6,7,8,9,...,100,101,102,103,104,105,106,107,108,109
sales_city,None,San Francisco,Mexico City,Los Angeles,Guadalajara,Vancouver,Victoria,San Diego,Coronado,National City,...,Royal Oak,Sooke,Langford,Cliffside,Metchosin,Shawnee,San Andres,Tixapan,Santa Anita,Santa Fe
sales_state_province,None,CA,DF,CA,Jalisco,BC,BC,CA,CA,CA,...,BC,BC,BC,BC,BC,BC,DF,DF,DF,DF
sales_district,No District,San Francisco,Mexico City,Los Angeles,Guadalajara,Vancouver,Victoria,San Diego,San Diego,San Diego,...,Victoria,Victoria,Victoria,Victoria,Victoria,Victoria,Mexico City,Mexico City,Mexico City,Mexico City
sales_region,No Region,Central West,Mexico Central,South West,Mexico West,Canada West,Canada West,South West,South West,South West,...,Canada West,Canada West,Canada West,Canada West,Canada West,Canada West,Mexico Central,Mexico Central,Mexico Central,Mexico Central
sales_country,No Country,USA,Mexico,USA,Mexico,Canada,Canada,USA,USA,USA,...,Canada,Canada,Canada,Canada,Canada,Canada,Mexico,Mexico,Mexico,Mexico
sales_district_id,0,123,118,116,114,128,129,133,133,133,...,129,129,129,129,129,129,118,118,118,118

In [143]:
tdf.shape

(8, 110)

I have learned about the follwoing things while working on this assignments.

- **Jupyter Notebook**: How easy it is to write codes to work, play and visualize data using it.
- **NumPy**: It is a mathematical library which provides vector and array (multidimensional) operations like sorting, selection required for Linear Algebra, Statistical Analysis etc.
- **Pandas**: It is a data analysis toolkit which helps to visualize the structured data and manipulate them.